### ISSUE TITLE
When changing the patch_window parameter on a Windows node, it attempts to run the exec block on line 304 which fails

### ISSUE THREAD

**Issue by mike406** [albatrossflavour/puppet_os_patching#211] opened 2022-01-29 19:39 UTC
```
Info: Applying configuration version '1643484471'
Notice: /Stage[main]/Os_patching/File[C:/ProgramData/os_patching/patch_window]/content:

Info: Computing checksum on file C:/ProgramData/os_patching/patch_window
Info: /Stage[main]/Os_patching/File[C:/ProgramData/os_patching/patch_window]: Filebucketed C:/ProgramData/os_patching/patch_window to puppet with sum 9e5b62c981d36cefe5407148880f8681
Notice: /Stage[main]/Os_patching/File[C:/ProgramData/os_patching/patch_window]/content: content changed '{md5}9e5b62c981d36cefe5407148880f8681' to '{md5}399a3848c3aa2bb4401c7204b6e0246b'
Info: /Stage[main]/Os_patching/File[C:/ProgramData/os_patching/patch_window]: Scheduling refresh of Exec[os_patching::exec::fact_upload]
Error: /Stage[main]/Os_patching/Exec[os_patching::exec::fact_upload]: Failed to call refresh: No such file or directory - CreateProcess
Error: /Stage[main]/Os_patching/Exec[os_patching::exec::fact_upload]: No such file or directory - CreateProcess
Info: Class[Os_patching]: Unscheduling all events on Class[Os_patching]
Notice: Applied catalog in 28.64 seconds
```

PuppetDB reports the error occurring at: `/etc/puppetlabs/code/environments/production/modules/os_patching/manifests/init.pp:304`

**Comment by kdimitrov-godaddy** [comment] 2022-03-30 13:59
I've been faced with the same issue, you managed to find a solution @mike406?

**Comment by DimitrovK** [comment] 2022-03-30 14:00
Did you manage to find a solution to the described problem @mike406?

**Comment by mike406** [comment] 2022-03-31 01:01
> Did you manage to find a solution to the described problem @mike406?

The issue is because the exec block at that line in the manifest uses hard coded linux paths which is why it fails on Windows. This exec block needs to be removed from this spot and incorporated into the conditional logic structure a few lines after so it runs correctly for Linux and Windows kernels

**Comment by albatrossflavour** [comment] 2022-03-31 10:22
Hey folks, sorry for the delay in responding.  As you likely know, `os_patching` was folded into Puppet Enterprise as `pe_patch`.  I'm going to be retrofitting some of the fixes that were made to `pe_patch` back into `os_patching` in the next couple of weeks, including one for this issue.

**Comment by albatrossflavour** [comment] 2022-08-08 05:19
I'm struggling to recreate this one.  I can see what you're saying the issue is, but the current version works on my windows setup.  I can see that in `pe_patch` we have added the `$fact_dir` into the `path` parameter of the exec, but that shouldn't make any difference.

Is it still causing an issue?

**Comment by gmenuel** [comment] 2022-08-08 09:39
Hi,
I'm also having this error, and while fiddling with the code I've found the problem, windows doesn't seem to like having a command in single quotes. Replacing the command in the Exec[$fact_upload_exec] declaration by :
`command     => [$puppet_binary, 'facts', 'upload'],`

seems to solve the problem (and still works on Linux).

**Comment by albatrossflavour** [comment] 2022-08-09 04:14
Going the array route is a clean solution, but lacks backward compatibility.

I'm testing on the packaged `puppet` agent on an ubuntu server and it is 5.5.2, which can't do arrays in exec commands.  I seem to recall that windows doesn't like them either, but looks like you're using them ok @gmenuel.

The fix for this in `pe_patch` was a bit more complex too.  I'm still looking at it but I'm open to ideas

**Comment by albatrossflavour** [comment] 2022-08-09 04:35
Can you try branch https://github.com/albatrossflavour/puppet_os_patching/tree/211-when-changing-the-patch_window-parameter-on-a-windows-node-it-attempts-to-run-the-exec-block-on-line-304-which-fails and see if that changes anything?  If not, can you punt me the logs from the runs?

**Comment by gmenuel** [comment] 2022-08-10 13:47
Hi, I've tested your branch and it doesn't work either. What should work is replaced the single quotes by double quotes surrounding the ${puppet_binary}

The log from the error (same as before):
```
Notice: /Stage[main]/Os_patching/File[C:/ProgramData/os_patching/patch_window]/ensure: defined content as '{sha256}ab8e18ef4ebebeddc0b3152ce9c9006e14fc05242e3fc9ce32246ea6a9543074' (corrective)
Info: /Stage[main]/Os_patching/File[C:/ProgramData/os_patching/patch_window]: Scheduling refresh of Exec[os_patching::exec::fact_upload]
Error: /Stage[main]/Os_patching/Exec[os_patching::exec::fact_upload]: Failed to call refresh: No such file or directory - CreateProcess
Error: /Stage[main]/Os_patching/Exec[os_patching::exec::fact_upload]: No such file or directory - CreateProcess
Info: Class[Os_patching]: Unscheduling all events on Class[Os_patching]
```

**Closed** 2023-02-14 13:07 UTC
Labels: bug, question
